---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: self-signer
spec:
  selfSigned: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: rootca
spec:
  secretName: rootca
  issuerRef:
    name: self-signer
  commonName: "ca.self-signer.cert-manager"
  isCA: true
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: nats-ca
spec:
  ca:
    secretName: rootca
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: nats-server-tls
spec:
  secretName: nats-server-tls
  duration: 2160h # 90 days
  renewBefore: 240h # 10 days
  issuerRef:
    name: nats-ca
    kind: Issuer
  usages:
  - signing
  - key encipherment
  - server auth
  - client auth
  organization:
  - Your organization
  commonName: nats.nats-helm.svc.cluster.local
  dnsNames:
  - nats.nats-helm.svc
  - nats-0.nats.nats-helm.svc
  - nats-1.nats.nats-helm.svc
  - nats-2.nats.nats-helm.svc
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: nats-client-tls
spec:
  secretName: nats-client-tls
  duration: 2160h # 90 days
  renewBefore: 240h # 10 days
  issuerRef:
    name: nats-ca
    kind: Issuer
  usages:
  - server auth
  organization:
  - Your organization
  commonName: nats.nats-helm.svc.cluster.local
  dnsNames:
  - nats.nats-helm.svc  