apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    cloud: Amazon
    name: {{ template "acm-aws-cluster.fullname" . }}
    vendor: OpenShift
    cluster.open-cluster-management.io/clusterset: gdw
    cluster.open-cluster-management.io/submariner-agent: "true"
  name: {{ template "acm-aws-cluster.fullname" . }}
spec:
  hubAcceptsClient: true