apiVersion: submarineraddon.open-cluster-management.io/v1alpha1
kind: SubmarinerConfig
metadata:
  name: subconfig
spec:
  credentialsSecret:
     name: {{ template "acm-aws-cluster.fullname" . }}-aws-credentials
  subscriptionConfig:
    startingCSV: submariner.v0.8.1    