apiVersion: submarineraddon.open-cluster-management.io/v1alpha1
kind: SubmarinerConfig
metadata:
  name: subconfig
spec:
  credentialsSecret:
     name: {{ .Release.Namespace }}-azure-credentials
  subscriptionConfig:
    startingCSV: submariner.v0.8.1    