## mandatory fields
# region: ""
# baseDomain: ""
# sshKey: ""
# sshPubKey: ""
# baseDomainResourceGroupName: ""
# azr_sa_json: ""
# docker_pull_secret: ""
# clusterReleaseImage: ""


install_config:
  apiVersion: v1
  metadata:
    #added by template
    name: ""
  #added by template  
  baseDomain: ""
  controlPlane:
    hyperthreading: Enabled
    name: master
    replicas: 3
    platform: 
      azure:
        osDisk:
          diskSizeGB: 128
        type:  Standard_D4s_v3
  compute:
  - hyperthreading: Enabled
    name: worker
    replicas: 3
    platform: 
      azure:
        type:  Standard_D2s_v3
        osDisk:
          diskSizeGB: 128
        zones:
        - "1"
        - "2"
        - "3"      
  networking:
    clusterNetwork:
      # added by template
    - cidr: ""
      hostPrefix: 23
    #machineCIDR: ${node_cidr}
    networkType: OpenShiftSDN
    serviceNetwork: []
      # added by template
  platform: {}
      # added by template
  pullSecret: "" # skip, hive will inject based on it's secrets
  # added by template
  sshKey: ""
