apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  clusterIP: None
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: keycloak
  type: ClusterIP