apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: keycloak
  type: ClusterIP
---  
apiVersion: v1
kind: Service
metadata:
  name: keycloak-jgroups
spec:
  clusterIP: None
  ports:
  - name: jgroups
    port: 7800
    protocol: TCP
    targetPort: 7800
  selector:
    app: keycloak
  type: ClusterIP  