apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
spec:
  replicas: 2
  selector:
    matchLabels:
      app: keycloak
  serviceName: keycloak-jgroups
  template:
    metadata:
      labels:
        app: keycloak        
    spec:
      containers:
      - image: quay.io/raffaelespazzoli/keycloak.x:{{ .Values.image.tag }}
        imagePullPolicy: Always
        name: keycloak
        args:
        - "start"
        - "--verbose"
        ports:
        - name: https
          containerPort: 8443
          protocol: TCP
        - name: jgroups
          containerPort: 7800
          protocol: TCP          
        volumeMounts:
        - mountPath: /certs
          name: certs
          readOnly: true
        - mountPath: /vault-certs
          name: vault-certs
          readOnly: true          
        - mountPath: /opt/keycloak/conf
          name: config
          readOnly: true
        env:  
        - name: KEYCLOAK_ADMIN
          value: admin 
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: admin
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_NAME
          value: {{ .Values.cluster }}
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName                          
      volumes:
      - name: config
        configMap:
          name: application-properties
      - name: certs
        secret:
          defaultMode: 420
          secretName: keycloak-tls
      - name: vault-certs
        secret:
          defaultMode: 420
          secretName: vault-ca-tls          