apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: {{ .Values.clusterName }}
  name: {{ .Values.clusterName }}-{{ .Values.machinePurpose }}-{{ .Values.zone }}
  namespace: openshift-machine-api
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: {{ .Values.clusterName }}
      machine.openshift.io/cluster-api-machineset: {{ .Values.clusterName }}-{{ .Values.machinePurpose }}-{{ .Values.zone }}
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: {{ .Values.clusterName }}
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: {{ .Values.machinePurpose }}
        machine.openshift.io/cluster-api-machineset: {{ .Values.clusterName }}-{{ .Values.machinePurpose }}-{{ .Values.zone }}
    spec:
      metadata: 
        labels:
          workload: {{ .Values.machinePurpose }}
      taints:
      - effect: NoSchedule
        key: workload
        value: {{ .Values.machinePurpose }}    
      providerSpec:
{{ if eq .Values.infrastructure "gcp" }}      
        value:
          machineType: {{ .Values.gcp.machineType }}
          userDataSecret:
            name: worker-user-data
          deletionProtection: false
          networkInterfaces:
            - network: {{ .Values.clusterName }}-network
              subnetwork: {{ .Values.clusterName }}-worker-subnet
          credentialsSecret:
            name: gcp-cloud-credentials
          zone: {{ .Values.zone }}
          canIPForward: false
          metadata:
            creationTimestamp: null
          projectID: {{ .Values.gcp.projectID }}
          region: {{ .Values.region }}
          kind: GCPMachineProviderSpec
          disks:
            - autoDelete: true
              boot: true
              image: {{ .Values.gcp.image }}
              labels: null
              sizeGb: 128
              type: pd-ssd
          tags:
            - {{ .Values.clusterName }}-worker
          serviceAccounts:
            - email: {{ .Values.clusterName }}-w@gc-acm-leads.iam.gserviceaccount.com
              scopes:
                - 'https://www.googleapis.com/auth/cloud-platform'
          apiVersion: gcpprovider.openshift.io/v1beta1
{{ end }}
{{ if eq .Values.infrastructure "aws" }}      
        value:
          ami:
            id: {{ .Values.aws.ami }}
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
          - ebs:
              encrypted: true
              iops: 2000
              kmsKey:
                arn: ""
              volumeSize: 100
              volumeType: io1
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: {{ .Values.clusterName }}-worker-profile
          instanceType: {{ .Values.aws.instanceType }}
          kind: AWSMachineProviderConfig
          metadata:
            creationTimestamp: null
          placement:
            availabilityZone: {{ .Values.zone }}
            region: {{ .Values.region }}
          securityGroups:
          - filters:
            - name: tag:Name
              values:
              - {{ .Values.clusterName }}-worker-sg
          subnet:
            filters:
            - name: tag:Name
              values:
              - {{ .Values.clusterName }}-private-{{ .Values.zone }}
          tags:
          - name: kubernetes.io/cluster/{{ .Values.clusterName }}
            value: owned
          userDataSecret:
            name: worker-user-data
{{ end }}            