apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-credentials
stringData:
{{ if eq .Values.infrastructure "aws"}}
  aws_access_key_id: {{ .Values.aws.id }} 
  aws_secret_access_key: {{ .Values.aws.key }}
{{ end }}
{{ if eq .Values.infrastructure "azure"}}
  osServicePrincipal.json: {{ .Values.azr.sa_json | toJson | toJson }}
{{ end }}
{{ if eq .Values.infrastructure "gcp"}}
  osServiceAccount.json: {{ .Values.gcp.sa_json | toJson }}
{{ end }}

