
{{ $myDict := .Values.install_config }}

{{- if .Values.fullnameOverride }}
{{ $_ := set $myDict.metadata "name" (.Values.fullnameOverride | trunc 63 | trimSuffix "-") }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{ $_ := set $myDict.metadata "name" (.Release.Name | trunc 63 | trimSuffix "-") }}
{{- else }}
{{ $_ := set $myDict.metadata "name" (printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-") }}
{{- end }}
{{- end }}

{{ $clusterNetworkDict:= dict "cidr" .Values.cluster_network_cidr "hostprefix" 23 }}
{{ $_ := set $myDict "baseDomain" .Values.baseDomain }}

{{ if eq .Values.infrastructure "aws" }}
{{ $awsDict := dict "region" .Values.region }} 
{{ $_ := set $myDict.platform "aws" $awsDict }} 
{{ end }}
{{ if eq .Values.infrastructure "azure" }}
{{ $azrDict := dict "region" .Values.region "baseDomainResourceGroupName" .Values.azr.baseDomainResourceGroupName }}  
{{ $_ := set $myDict.platform "azure" $azrDict }}
{{ end }}
{{ if eq .Values.infrastructure "gcp" }}
{{ $gcpDict := dict "region" .Values.region "projectID" .Values.gcp.projectID }}  
{{ $_ := set $myDict.platform "gcp" $gcpDict }}
{{ end }}
 
{{ $_ := set $myDict "sshKey" .Values.sshPubKey }}  
{{ $_ := set $myDict.networking "serviceNetwork" (list .Values.service_network_cidr) }}
{{ $_ := set $myDict.networking "clusterNetwork" (list $clusterNetworkDict) }}
{{ $_ := set $myDict.networking "machineCIDR" .Values.node_cidr }}

{{ if eq .Values.infrastructure "aws"}}
{{ $_ := set $myDict.controlPlane.platform "aws" .Values.hive.aws.controlPlane }} 
{{ $_ := set (index $myDict.compute 0).platform "aws" .Values.hive.aws.compute }} 
{{ end }}
{{ if eq .Values.infrastructure "azure"}}
{{ $_ := set $myDict.controlPlane.platform "azure" .Values.hive.azr.controlPlane }} 
{{ $_ := set (index $myDict.compute 0).platform "azure" .Values.hive.azr.compute }}
{{ end }}
{{ if eq .Values.infrastructure "gcp"}}
{{ $_ := set $myDict.controlPlane.platform "gcp" .Values.hive.gcp.controlPlane }} 
{{ $_ := set (index $myDict.compute 0).platform "gcp" .Values.hive.gcp.compute }}
{{ end }}


apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-install-config
type: Opaque
data:
  install-config.yaml: {{ $myDict | toPrettyJson | b64enc }}
