apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: {{ .Release.Name }}-worker
spec:
  clusterDeploymentRef:
    name: {{ .Release.Name }}
  name: worker
  platform:
    {{ if eq .Values.infrastructure "aws"}}
    aws:
      rootVolume:
        iops: 100
        size: 100
        type: gp2
      type: m5.large
    {{ end }}
    {{ if eq .Values.infrastructure "azure"}}
    azure:
      osDisk:
        diskSizeGB: 128
      type: Standard_D2s_v3
      zones:
      - "1"
      - "2"
      - "3"
    {{ end }}
    {{ if eq .Values.infrastructure "gcp"}}
    gcp:
      type: n1-standard-4
    {{ end }}  
  replicas: 3