{{ if .Values.submariner.enableOperator }}
apiVersion: submarineraddon.open-cluster-management.io/v1alpha1
kind: SubmarinerConfig
metadata:
  name: submariner
spec:
  credentialsSecret:
     name: {{ .Release.Name }}-credentials
  cableDriver: vxlan
  NATTEnable: false

  gatewayConfig:
  {{ if eq .Values.infrastructure "aws"}}
    aws:
      instanceType: {{ .Values.submariner.aws.machineType }}
  {{ end }}      
    gateways: 1
{{ end }}  