{{ if .Values.submariner.enableOperator }}
apiVersion: submarineraddon.open-cluster-management.io/v1alpha1
kind: SubmarinerConfig
metadata:
  name: subconfig
spec:
  credentialsSecret:
     name: {{ .Release.Name }}-credentials
  subscriptionConfig:
    startingCSV: submariner.v0.9.0    
{{ end }}