## mandatory fields
# region: ""
# baseDomain: ""
# sshKey: ""
# sshPubKey: ""
# aws_id: ""
# aws_key: ""
# docker_pull_secret: ""
# clusterReleaseImage: ""


install_config:
  apiVersion: v1
  metadata:
    #added by template
    name: ""
  #added by template  
  baseDomain: ""
  controlPlane:
    hyperthreading: Enabled
    name: master
    replicas: 3
    platform:
      aws:
        rootVolume:
          iops: 4000
          size: 100
          type: io1
        type: m5.xlarge
  compute:
  - hyperthreading: Enabled
    name: worker
    replicas: 3
    platform:
      aws:
        rootVolume:
          iops: 2000
          size: 100
          type: io1
        type: m5.large
  networking:
    clusterNetwork:
      # added by template
    - cidr: ""
      hostPrefix: 23
    machineCIDR: ${node_cidr}
    networkType: OpenShiftSDN
    serviceNetwork:
      # added by template
    - ""
  platform:
    aws:
      # added by template
      region: ""
  pullSecret: "" # skip, hive will inject based on it's secrets
  # added by template
  sshKey: ""
