labels: 
  workload: yugabyte
taints: 
- key: workload
  value: yugabyte
  effect: NoSchedule
purpose: yugabyte
clusterRef: ${cluster}
infrastructure: ${infrastructure}
replicas: 3
azr:
  machineType: Standard_F16s_v2
gcp:
  machineType: c2-standard-16
aws:
  machineType: c5d.4xlarge 