# this image has the bugfix
# isanketh/yugabyte:dmitry-tls-write-txn-fix-2.5.2.0-b0

infrastructure: ${infrastructure} 

isMultiAz: true

# Image:
#   repository: "isanketh/yugabyte"
#   tag: dmitry-tls-write-txn-fix-2.5.2.0-b0
#   pullPolicy: IfNotPresent

masterAddresses: yb-master-0.cluster1.yb-masters.yugabyte.svc.clusterset.local:7100,yb-master-0.cluster2.yb-masters.yugabyte.svc.clusterset.local:7100,yb-master-0.cluster3.yb-masters.yugabyte.svc.clusterset.local:7100

storage:
  master:
    size: 80Gi
    storageClass: "yugabyte"
  tserver:
    size: 300Gi
    storageClass: "yugabyte"

replicas:
  master: 1
  tserver: 3
  totalMasters: 3

resource:
  master:
    requests:
      cpu: 4
      memory: 4Gi
    limits:
      cpu: null
      memory: 4Gi
  tserver:
    requests:
      cpu: 10
      memory: 22Gi
    limits:
      cpu: null
      memory: 22Gi       

tls:
  enabled: true

base_domain: ${global_base_domain}
cluster: ${cluster}
domainName: "clusterset.local"
tolerations:
  - key: "workload"
    operator: "Equal"
    value: "yugabyte"
    effect: "NoSchedule"
nodeSelector:
  workload: yugabyte

uid: ${uid}
guid: ${guid}  

serviceMonitor:
  enabled: true
  extraLabels:
    release: prom

serviceEndpoints:
  - name: "yb-master-ui"
    type: ClusterIP
    app: "yb-master"
    ports:
      http-ui: "7000"

  - name: "yb-tserver-service"
    type: ClusterIP
    app: "yb-tserver"
    ports:
      tcp-yql-port: "9042"
      tcp-yedis-port: "6379"
      tcp-ysql-port: "5433"    