kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: yugabyte
  annotations:
    cert-utils-operator.redhat-cop.io/certs-from-secret: yugabyte-master-ui-tls
    global-load-balancer-operator.redhat-cop.io/load-balancing-policy: Latency
    global-load-balancer-operator.redhat-cop.io/health-check: '{"httpGet":{"path":"","port":443,"scheme":"HTTPS"},"timeoutSeconds":1,"periodSeconds":10,"successThreshold":1,"failureThreshold":3}'
  labels:
    route-type: global      
spec:
  host: yugabyte.{{ .Values.base_domain }} 
  to:
    kind: Service
    name: yb-master-ui
    weight: 100
  port:
    targetPort: http-ui
  wildcardPolicy: None
  tls:
    termination: edge
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: yugabyte-master-ui
spec:
  # Secret names are always required.
  secretName: yugabyte-master-ui-tls
  commonName: yugabyte.{{ .Values.base_domain }}
  usages:
    - server auth 
  dnsNames:    
  - yugabyte.{{ .Values.base_domain }}
  duration: 168h
  renewBefore: 1h
  issuerRef:
    name: vault-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io

