apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Namespace }}-docker-pull-secret
stringData:
  .dockerconfigjson: {{ .Values.docker_pull_secret | toJson | toJson }}
type: kubernetes.io/dockerconfigjson