
{{ $myDict := .Values.install_config }}

{{- if .Values.fullnameOverride }}
{{ $_ := set $myDict.metadata "name" (.Values.fullnameOverride | trunc 63 | trimSuffix "-") }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{ $_ := set $myDict.metadata "name" (.Release.Name | trunc 63 | trimSuffix "-") }}
{{- else }}
{{ $_ := set $myDict.metadata "name" (printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-") }}
{{- end }}
{{- end }}

{{ $clusterNetworkDict:= dict "cidr" .Values.cluster_network_cidr "hostprefix" 23 }}
{{ $_ := set $myDict "baseDomain" .Values.baseDomain }}
{{ $awsDict := dict "region" .Values.region "projectID" .Values.gcp_projectID }}  
{{ $_ := set $myDict.platform "gcp" $awsDict }}
{{ $_ := set $myDict "sshKey" .Values.sshPubKey }}  
{{ $_ := set $myDict.networking "serviceNetwork" (list .Values.service_network_cidr) }}
{{ $_ := set $myDict.networking "clusterNetwork" (list $clusterNetworkDict) }}
{{ $_ := set $myDict.networking "machineCIDR" .Values.node_cidr }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Namespace }}-install-config
type: Opaque
data:
  install-config.yaml: {{ $myDict | toPrettyJson | b64enc }}
