apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: {{ .Release.Namespace }}-worker
spec:
  clusterDeploymentRef:
    name: {{ .Release.Namespace }}
  name: worker
  platform:
    gcp:
      type: n1-standard-4
  replicas: 3
---
apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: {{ .Release.Namespace }}-submariner-gateway
spec:
  clusterDeploymentRef:
    name: {{ .Release.Namespace }}
  name: submariner-gateway
  platform:
    gcp:
      type: c2-standard-8
  replicas: 1  
  labels:
    submariner.io/gateway: 'true'
  taints:
  - key: "submariner.io/gateway"
    value: 'true'
    effect: NoSchedule  