{{ if .Values.submariner.enabled }}
apiVersion: submarineraddon.open-cluster-management.io/v1alpha1
kind: SubmarinerConfig
metadata:
  name: subconfig
spec:
  credentialsSecret:
     name: {{ .Release.Namespace }}-gcp-credentials
  subscriptionConfig:
    startingCSV: submariner.v0.8.1    
{{ end }}