## mandatory fields
# region: ""
# baseDomain: ""
# sshKey: ""
# sshPubKey: ""
# gcp_sa_json: ""
# gcp_projectID: ""
# docker_pull_secret: ""
# clusterReleaseImage: ""


install_config:
  apiVersion: v1
  metadata:
    #added by template
    name: ""
  #added by template  
  baseDomain: ""
  controlPlane:
    hyperthreading: Enabled
    name: master
    replicas: 3
    platform:
      gcp:
        type: n1-standard-4
  compute:
  - hyperthreading: Enabled
    name: worker
    replicas: 3
    platform:
      gcp:
        type: n1-standard-4
  networking:
    clusterNetwork:
      # added by template
    - cidr: ""
      hostPrefix: 23
    #machineCIDR: ${node_cidr}
    networkType: OpenShiftSDN
    serviceNetwork:
      # added by template
    - ""
  platform:
    gcp:
      # added by template
      projectID: ""
      # added by template
      region: ""
  pullSecret: "" # skip, hive will inject based on it's secrets
  # added by template
  sshKey: ""

submariner:
  enabled: true