apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: etcd
spec:
  # Secret names are always required.
  secretName: etcd-tls
  commonName: node
  usages:
    - server auth
    - client auth  
  dnsNames:
{{- $namespace := .Release.Namespace  -}}
{{- $replicas:= .Values.replicas -}}
{{- range .Values.clusterNames }}
{{- $cluster:= . }}    
{{- range until (int $replicas) }}
    - etcd-{{ . }}.{{ $cluster }}.etcd.{{ $namespace }}.svc.clusterset.local
{{- end }}
{{- end }}
{{- range until (int $replicas) }}
    - etcd-{{ . }}.etcd.{{ $namespace }}.svc.cluster.local
{{- end }}
    - etcd.{{ $namespace }}.svc.clusterset.local
    - etcd.{{ $namespace }}.svc.cluster.local 
  duration: 168h
  renewBefore: 1h
  issuerRef:
    name: vault-issuer
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io