apiVersion: v1
kind: Service
metadata:
  name: etcd
spec:
  clusterIP: None
  ports:
  - port: 2380
    targetPort: 2380
    name: cluster-tls
    protocol: TCP
  - port: 2379
    targetPort: 2379
    name: clients-tls
    protocol: TCP 
  selector:
    app: etcd
  sessionAffinity: None
  type: ClusterIP