configuration:
  akhq:
    connections:
      kafka-cluster:
        properties:
          bootstrap.servers: "kafka-0.${cluster}.kafka.kafka.svc.clusterset.local:9093,kafka-1.${cluster}.kafka.kafka.svc.clusterset.local:9093,kafka-2.${cluster}.kafka.kafka.svc.clusterset.local:9093"
          security.protocol: SSL
          ssl.truststore.type: JKS
          ssl.truststore.location: /certs/truststore.jks
          ssl.truststore.password: changeit
          ssl.endpoint.identification.algorithm: ""

extraVolumes:
- name: certs
  secret:
    secretName: akhq-tls

extraVolumeMounts:
- mountPath: /certs
  name: certs           