apiVersion: v1
kind: Service
metadata:
  name: kafka-clients
spec:
  ports:
  - name: broker-tls
    port: 9091
    protocol: TCP
    targetPort: 9091
  - name: controller-tls
    port: 9092
    protocol: TCP
    targetPort: 9092
  - name: client-tls
    port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    app: kafka
  sessionAffinity: None
  type: ClusterIP
---    
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: kafka
spec:
  clusterIP: None
  ports:
  - name: broker-tls
    port: 9091
    protocol: TCP
    targetPort: 9091
  - name: controller-tls
    port: 9092
    protocol: TCP
    targetPort: 9092
  - name: client-tls
    port: 9093
    protocol: TCP
    targetPort: 9093
  publishNotReadyAddresses: true
  selector:
    app: kafka
  sessionAffinity: None
  type: ClusterIP