apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: zookeeper
spec:
  clusterIP: None
  ports:
  - name: tcp-clients
    port: 2181
    protocol: TCP
    targetPort: 2181
  - name: tcp-clustering
    port: 2888
    protocol: TCP
    targetPort: 2888
  - name: tcp-election
    port: 3888
    protocol: TCP
    targetPort: 3888
  - name: admin
    port: 8080
    protocol: TCP
    targetPort: 8080     
  publishNotReadyAddresses: true
  selector:
    app: zookeeper
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-client
spec:
  ports:
  - name: tcp-clients
    port: 2181
    protocol: TCP
    targetPort: 2181
  selector:
    app: zookeeper
  sessionAffinity: None
  type: ClusterIP  